version: '3'

networks:
  default:
    driver: bridge

services:
  postgres:
    image: postgres:alpine
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=homestead
      - POSTGRES_USER=homestead
      - POSTGRES_PASSWORD=qwe123asd
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - default

  php-cli:
    build:
      context: ./docker/php-cli
      args:
        - INSTALL_XDEBUG=true
    volumes:
      - ./:/var/www:cached
    command: sh -c 'composer install; /wait-for-it.sh postgres:5432 -t 60; php artisan migrate; /bin/bash'
    tty: true
    networks:
      - default